export {default as Address} from './Address'
export {default as Home} from './Home'
export {default as Payment} from './Payment'
export {default as ProductListPage} from './ProductListPage'
export {default as Shipping} from './Shipping'
export {default as CheckOutPage} from './CheckOutPage'
export {default as PaymentDetailsPage} from './PaymentDetailsPage'
export {default as ShippingDetails} from './ShippingDetails'